### PR TITLE
change select sighting context fields to optional

### PR DESCRIPTION
**Pull request by t2sw**
Per 8427 make the following changes to sighting context

Make [HTTPType > :method](https://github.com/threatgrid/ctim/blob/f6529ae7f56964c41fb69a0db06b3aa5465b815b/src/ctim/schemas/sighting/context.cljc#L163C33-L163C33) optional
Make RegistryDeleteType  > :registry_value optional
Make [RegistrySetType > :registry_data](https://github.com/threatgrid/ctim/blob/f6529ae7f56964c41fb69a0db06b3aa5465b815b/src/ctim/schemas/sighting/context.cljc#L196) optional

### CODE REVIEW

**Review by msprunck — DISMISSED** [review]
LGTM!

**Comment by samwagg** [comment]
Do we need to make the same changes to casebook?

**Comment by t2sw** [comment]
@samwagg @msprunck i will make the corresponding changes for casebook

**Comment by msprunck** [comment]
> @samwagg @msprunck i will make the corresponding changes for casebook

Could you explain how this change can also be applied to Casebooks?

**Comment by samwagg** [comment]
> > @samwagg @msprunck i will make the corresponding changes for casebook
> 
> Could you explain how this change can also be applied to Casebooks?

I'm not very familiar with Casebook. I just noticed that casebook.md also has this HTTPType, and the doc wasn't updated in this PR. Looking closer, it seems that Casebook.md includes the `sighting` schema. So I assume the doc just needs to be regenerated from the same schema?

But I am totally open to the idea that I'm just confused :)

**Comment by samwagg** [comment]
> > > @samwagg @msprunck i will make the corresponding changes for casebook
> > 
> > 
> > Could you explain how this change can also be applied to Casebooks?
> 
> I'm not very familiar with Casebook. I just noticed that casebook.md also has this HTTPType, and the doc wasn't updated in this PR. Looking closer, it seems that Casebook.md includes the `sighting` schema. So I assume the doc just needs to be regenerated from the same schema?
> 
> But I am totally open to the idea that I'm just confused :)

I suppose the same is true of Bundle. Are there others?

**Comment by samwagg** [comment]
Just Bundle and Casebook. I pulled down the branch and ran `lein doc` to confirm.

**Review by msprunck — APPROVED** [review]
LGTM!

**Pull request merged**
