### PR TITLE
Bundle example with asset-refs

### PR DESCRIPTION
**Pull request by agzam**
Closes: https://github.com/threatgrid/ctim/issues/334

No QA required.

### CODE REVIEW

**Review by ereteog — COMMENTED** [review]
The problem to use transient ids in the `asset_ref` field for [`asset-properties`](https://github.com/threatgrid/ctim/blob/9fff33b81c705c649ad8ea8d9331fa091102f121/src/ctim/schemas/asset_properties.cljc#L37) and [`asset-mapping`](https://github.com/threatgrid/ctim/blob/9fff33b81c705c649ad8ea8d9331fa091102f121/src/ctim/schemas/asset_mapping.cljc#L48) is only the schema of this field which is currently [`ref-for-type`](https://github.com/threatgrid/ctim/blob/9fff33b81c705c649ad8ea8d9331fa091102f121/src/ctim/schemas/asset.cljc#L47) that basically [expects a string url](https://github.com/threatgrid/ctim/blob/9fff33b81c705c649ad8ea8d9331fa091102f121/src/ctim/schemas/common.cljc#L59).
In order to enable us to use a transient id for `asset_ref` field, you must replace it by a [`c/Reference`](https://github.com/threatgrid/ctim/blob/9fff33b81c705c649ad8ea8d9331fa091102f121/src/ctim/schemas/common.cljc#L46) that accepts transient id like [`source_ref` and `target_ref` of relationship](https://github.com/threatgrid/ctim/blob/9fff33b81c705c649ad8ea8d9331fa091102f121/src/ctim/schemas/relationship.cljc#L19).

**Comment by agzam** [comment]
I did this: https://github.com/threatgrid/ctim/pull/335/commits/f6f80289b36e6992e91113208a68284f52203e7e

Do you think I should revert my changes around `bundle-maximal`? Leave it with the long IDs, as it was?
I think it'd be nice to have a "proper" bundle example with transient IDs. No?

**Review by ereteog — COMMENTED** [review]
> I did this: f6f8028

Nice 

> Do you think I should revert my changes around bundle-maximal? Leave it with the long IDs, as it was?
I think it'd be nice to have a "proper" bundle example with transient IDs. No?

Yes please rever it. the `*_refs` fields are intented to lighten bundle responses with only the ids. Thus it is mainly long ids that are expected, since they contain those from the response.

**Comment by agzam** [comment]
> Yes please revert it.

I have reverted all the changes in Bundle examples. Now I need to bump the version, merge it and deploy new version.

**Comment by ereteog** [comment]
LGTM

**Review by ereteog — APPROVED** [review]
LGTM

**Pull request merged**
